In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

In [35]:
print("Input your model assumption values")
growth_year = input("Enter Growth Year ")
transition_year = input("Enter Transition Year ")
long_term_growth_rate = input("Enter Long Term Growth Rate ")
closing_price = input("Enter Closing Price ")
bond_rate = input("Enter Bond Rate ")
beta = input("Enter Beta ")
risk_premium = input("Enter Risk Premium ")
payout_during_growth_year = input("Enter Payout During Growth Rate ")
payout_at_maturity = input("Enter Payout at Maturity ")
growth_rate_at_maturity = input("Enter Growth Rate at Maturity ")
earning_per_share_FY1 = input("Enter Earning per Share FY1 ")
earning_per_share_FY2 = input("Enter Earning per Share FY2 ")
earning_per_share_FY3 = input("Enter Earning per Share FY3 ")
 
# Calculate Annual Growth rate decrease (long term growth rate - growht rate at maturity)/ transitional years 
annual_growth_rate_decrease = (float(long_term_growth_rate) - float(growth_rate_at_maturity)) / float(transition_year)
annual_growth_rate_decrease = round(annual_growth_rate_decrease/100, 8)
print("Annual Growth rate decrease", annual_growth_rate_decrease)

# Calculate Annual payout decrease ((payout during growth years - payout at maturity )/ transitional years)
annual_payout_decrease = (float(payout_during_growth_year) - float(payout_at_maturity))/ float(transition_year)
annual_payout_decrease = round(annual_payout_decrease/100, 8)
print("Annual payout decrease", annual_payout_decrease)

# Calculate Cost of equity (k) (bond rate + risk premium ) 
cost_of_equity = float(bond_rate) + float(risk_premium)
print("Cost of Equity (K)", cost_of_equity)
cost_of_equity_in_decimal = round((cost_of_equity / 100), 8)
print("Cost of Equity (K) in Decimal", cost_of_equity_in_decimal)

# Calculate Growth rate (Growth rate is the same as Growth Rate at Maturity in decimal)
growth_rate = round(float(growth_rate_at_maturity) / 100, 8)
print("Growth Rate", growth_rate)

# Calculate K-G  ( cost of equity - growth rate) in decimal 
k_g = round(cost_of_equity_in_decimal - growth_rate, 6)
print("K-G", k_g)

Input your model assumption values


Enter Growth Year  9
Enter Transition Year  8
Enter Long Term Growth Rate  9.687
Enter Closing Price  62.85
Enter Bond Rate  1.899
Enter Beta  0.984
Enter Risk Premium  7.703
Enter Payout During Growth Rate  70.749
Enter Payout at Maturity  45
Enter Growth Rate at Maturity  5.281
Enter Earning per Share FY1  2.458
Enter Earning per Share FY2  2.641
Enter Earning per Share FY3  2.821


Annual Growth rate decrease 0.0055075
Annual payout decrease 0.03218625
Cost of Equity (K) 9.602
Cost of Equity (K) in Decimal 0.09602
Growth Rate 0.05281
K-G 0.04321


In [77]:
# Calculate Growth Rate on Table (growth rate at previous year - annual growth rate decrease) 
years = np.arange(4, 21)
long_term_growth_rate_in_decimal = float(long_term_growth_rate)/100
growth_rate_list = []
x = 1
for growth in years:
    if x <= int(growth_year):
        growth_rate_list.append(long_term_growth_rate_in_decimal) 
    else: 
        trans_growth_rate = growth_rate_list[-1] - annual_growth_rate_decrease
        growth_rate_list.append(round(trans_growth_rate, 7))
    x+=1  
growth_rate_list.append(round(trans_growth_rate, 7))
growth_rate_list

[0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.09687,
 0.0913625,
 0.085855,
 0.0803475,
 0.07484,
 0.0693325,
 0.063825,
 0.0583175,
 0.05281,
 0.05281]

In [52]:
# Calculate EPS for this year (EPS for previous year *(1+ growht rate of present year))
eps_list = [float(earning_per_share_FY1), float(earning_per_share_FY2), float(earning_per_share_FY3)]
years = np.arange(0, 18)
for x in years:
    new_eps_value = eps_list[-1] * (1 + growth_rate_list[x])
    eps_list.append(new_eps_value)
    
eps_list = np.array(eps_list)
eps_list

array([ 2.458     ,  2.641     ,  2.821     ,  3.09427027,  3.39401223,
        3.7227902 ,  4.08341688,  4.47897748,  4.91285602,  5.38876439,
        5.91077399,  6.48335067,  7.07568579,  7.6831688 ,  8.3004922 ,
        8.92170104,  9.54026488, 10.14917228, 10.74104664, 11.30828131,
       11.90547165])

In [53]:
# Calculate Dividend Payout ratio (DPR of previous year - Annual payout Decrease)
dpr_list = [float(payout_during_growth_year)/100 for dpr_value in np.arange(int(growth_year)+3)]
for value in np.arange(8):
    new_dpr_value = dpr_list[-1] - round(annual_payout_decrease, 8)
    dpr_list.append(round(new_dpr_value, 8)) 
dpr_list.append(round(new_dpr_value, 8))
dpr_list = np.array(dpr_list)
dpr_list

array([0.70749   , 0.70749   , 0.70749   , 0.70749   , 0.70749   ,
       0.70749   , 0.70749   , 0.70749   , 0.70749   , 0.70749   ,
       0.70749   , 0.70749   , 0.67530375, 0.6431175 , 0.61093125,
       0.578745  , 0.54655875, 0.5143725 , 0.48218625, 0.45      ,
       0.45      ])

In [55]:
# Calculate the Dividend per Share (DPS) as (EPS * DPR )
dps_list = eps_list * dpr_list
dps_list[20] = round(dps_list[20] / k_g, 8)
dps_list

array([  1.73901042,   1.86848109,   1.99582929,   2.18916527,
         2.40122971,   2.63383684,   2.88897661,   3.16883177,
         3.47579651,   3.81249692,   4.18181349,   4.58690577,
         4.77823715,   4.94118031,   5.07103008,   5.16338987,
         5.21431525,   5.22045512,   5.179185  ,   5.08872659,
       123.98662905])

In [78]:
# Calculate PV (DPS at present year/ ( 1 + cost of equity) ^number of years till present)
years = np.arange(1, 22)
pv = [dps/((1 + cost_of_equity_in_decimal)**years[yr]) for yr, dps in enumerate(dps_list)]
pv = np.array(pv)
pv

array([ 1.58665939,  1.55543458,  1.51589093,  1.51706655,  1.51824309,
        1.51942054,  1.5205989 ,  1.52177817,  1.52295836,  1.52413947,
        1.52532149,  1.52650443,  1.45086656,  1.36890085,  1.28179626,
        1.19080117,  1.09719328,  1.00224925,  0.9072152 ,  0.81327896,
       18.0795156 ])

In [57]:
# Calculate sum of pv (Summation of PV at year 1 to Pv at year 21 )
sum_of_pv = round(np.sum(pv), 8)
sum_of_pv

45.54583302

In [79]:
growth_rate_list.insert(0, "")
growth_rate_list.insert(1, "")
growth_rate_list.insert(2, "")
growth_rate_list = np.array(growth_rate_list)
ddm_table = pd.DataFrame({"Years":years, "Growth Rate":growth_rate_list, "EPS":eps_list, "Dividend Payout Ratio":dpr_list, 
                          "DPS":dps_list, "PV":pv})
ddm_table

21 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


Years Growth Rate        EPS  Dividend Payout Ratio         DPS         PV
0       1               2.458000               0.707490    1.739010   1.586659
1       2               2.641000               0.707490    1.868481   1.555435
2       3               2.821000               0.707490    1.995829   1.515891
3       4     0.09687   3.094270               0.707490    2.189165   1.517067
4       5     0.09687   3.394012               0.707490    2.401230   1.518243
5       6     0.09687   3.722790               0.707490    2.633837   1.519421
6       7     0.09687   4.083417               0.707490    2.888977   1.520599
7       8     0.09687   4.478977               0.707490    3.168832   1.521778
8       9     0.09687   4.912856               0.707490    3.475797   1.522958
9      10     0.09687   5.388764               0.707490    3.812497   1.524139
10     11     0.09687   5.910774               0.707490    4.181813   1.525321
11     12     0.09687   6.483351               0.707490    4.586906   1.526504
12     13   0.0913625   7.075686               0.675304    4.778237   1.450867
13     14    0.085855   7.683169               0.643118    4.941180   1.368901
14     15   0.0803475   8.300492               0.610931    5.071030   1.281796
15     16     0.07484   8.921701               0.578745    5.163390   1.190801
16     17   0.0693325   9.540265               0.546559    5.214315   1.097193
17     18    0.063825  10.149172               0.514373    5.220455   1.002249
18     19   0.0583175  10.741047               0.482186    5.179185   0.907215
19     20     0.05281  11.308281               0.450000    5.088727   0.813279
20     21     0.05281  11.905472               0.450000  123.986629  18.079516

In [32]:
import yfinance as yf

# Define the ticker symbol
ticker_symbol = 'AAPL'  # Example: Apple Inc.
# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)
try:
    # Get cash flow data
    cash_flow = ticker.cashflow
    # Get balance sheet data
    balance_sheet = ticker.balance_sheet
    # Get the number of shares outstanding
    shares_outstanding = ticker.info.get('sharesOutstanding')
except Exception as e:
    print("An error occurred:", e)

In [33]:
# Print the cash flow data
fcf = cash_flow.loc["Free Cash Flow"].values
# Print the balance sheet data
total_debt = balance_sheet.loc['Total Debt'].values
cc_equivalent = balance_sheet.loc["Cash And Cash Equivalents"].values
print(fcf)
print(total_debt)
print(cc_equivalent)
print("Shares Outstanding:", shares_outstanding)

[99584000000.0 111443000000.0 92953000000.0 73365000000.0]
[111088000000.0 120069000000.0 124719000000.0 112436000000.0]
[29965000000.0 23646000000.0 34940000000.0 38016000000.0]
Shares Outstanding: 15441899520


In [ ]:
import numpy as np
import pandas as pd
import sys
import yfinance as yf

class DDM_DCF_model:
    def __init__(self):
        self.x = 0
        self.mainmenu()
    
    def mainmenu(self):
        option = input("Enter your operation:\n1. DDM model\n2. DCF model\n>>>")
        if option == "1":
            self.ddm_model()
        elif option == "2":
            self.dcf_model()
        else:
            print("Invalid option selected")
            self.mainmenu()
    
    def very_value(self):
        prompt_string = ["Enter Growth Year ", "Enter Transition Year ", "Enter Long Term Growth Rate ", "Enter Closing Price ", 
                         "Enter Bond Rate ", "Enter Beta ", "Enter Risk Premium ", "Enter Payout During Growth Rate ", "Enter Payout at Maturity ",
                        "Enter Growth Rate at Maturity ", "Enter Earning per Share FY1 ", "Enter Earning per Share FY2 ",
                        "Enter Earning per Share FY3 "]
        
        input_value = input(prompt_string[self.x])
        try:
            input_value = float(input_value)
            self.x +=1
        except:
            print("Input value not valid please ensure you enter number with no space")
            self.very_value()
        return input_value
        
    def ddm_model(self):
        print("Input your model assumption values. COUTION- Do not include space or % ")
        # self.growth_year = input("Enter Growth Year ")
        # self.transition_year = input("Enter Transition Year ")
        # self.long_term_growth_rate = input("Enter Long Term Growth Rate ")
        # self.closing_price = input("Enter Closing Price ")
        # self.bond_rate = input("Enter Bond Rate ")
        # self.beta = input("Enter Beta ")
        # self.risk_premium = input("Enter Risk Premium ") 
        # self.payout_during_growth_year = input("Enter Payout During Growth Rate ")
        # self.payout_at_maturity = input("Enter Payout at Maturity ")
        # self.growth_rate_at_maturity = input("Enter Growth Rate at Maturity ")
        # self.earning_per_share_FY1 = input("Enter Earning per Share FY1 ")
        # self.earning_per_share_FY2 = input("Enter Earning per Share FY2 ")
        # self.earning_per_share_FY3 = input("Enter Earning per Share FY3 ")
        self.growth_year = self.very_value()
        self.transition_year = self.very_value()
        self.long_term_growth_rate = self.very_value()
        print(self.long_term_growth_rate)
        self.closing_price = self.very_value()
        print(self.closing_price)
        self.bond_rate = self.very_value()
        self.beta = self.very_value()
        self.risk_premium = self.very_value()
        print(self.risk_premium)
        self.payout_during_growth_year = self.very_value()
        self.payout_at_maturity = self.very_value()
        self.growth_rate_at_maturity = self.very_value()
        self.earning_per_share_FY1 = self.very_value()
        self.earning_per_share_FY2 = self.very_value()
        self.earning_per_share_FY3 = self.very_value()
        
        self.get_constant_values()

    def get_constant_values(self):
        print("======================================================================")
        print("======================================================================")
        # Calculate Annual Growth rate decrease (long term growth rate - growht rate at maturity)/ transitional years 
        annual_growth_rate_decrease = (float(self.long_term_growth_rate) - float(self.growth_rate_at_maturity)) / float(self.transition_year)
        self.annual_growth_rate_decrease = round(annual_growth_rate_decrease/100, 8)
        print("Annual Growth rate decrease", self.annual_growth_rate_decrease)

        # Calculate Annual payout decrease ((payout during growth years - payout at maturity )/ transitional years)
        annual_payout_decrease = (float(self.payout_during_growth_year) - float(self.payout_at_maturity))/ float(self.transition_year)
        self.annual_payout_decrease = round(annual_payout_decrease/100, 8)
        print("Annual payout decrease", self.annual_payout_decrease)

        # Calculate Cost of equity (k) (bond rate + risk premium ) 
        self.cost_of_equity = float(self.bond_rate) + float(self.risk_premium)
        print("Cost of Equity (K)", str(self.cost_of_equity)+"%")
        self.cost_of_equity_in_decimal = round((self.cost_of_equity / 100), 8)
        print("Cost of Equity (K) in Decimal", self.cost_of_equity_in_decimal)

        # Calculate Growth rate (Growth rate is the same as Growth Rate at Maturity in decimal)
        self.growth_rate = round(float(self.growth_rate_at_maturity) / 100, 8)
        print("Growth Rate", self.growth_rate)

        # Calculate K-G  ( cost of equity - growth rate) in decimal 
        self.k_g = round(self.cost_of_equity_in_decimal - self.growth_rate, 6)
        print("K-G", self.k_g)
        
        self.calculate_ddm()

    def calculate_ddm(self):
        # Calculate Growth Rate on Table (growth rate at previous year - annual growth rate decrease) 
        years = np.arange(4, 21)
        long_term_growth_rate_in_decimal = float(self.long_term_growth_rate)/100
        growth_rate_list = []
        x = 1
        for growth in years:
            if x <= int(self.growth_year):
                growth_rate_list.append(long_term_growth_rate_in_decimal) 
            else: 
                trans_growth_rate = growth_rate_list[-1] - self.annual_growth_rate_decrease
                growth_rate_list.append(round(trans_growth_rate, 7))
            x+=1  
        growth_rate_list.append(round(trans_growth_rate, 7))

        # Calculate EPS for this year (EPS for previous year *(1+ growht rate of present year))
        eps_list = [float(self.earning_per_share_FY1), float(self.earning_per_share_FY2), float(self.earning_per_share_FY3)]
        years = np.arange(0, 18)
        for x in years:
            new_eps_value = eps_list[-1] * (1 + growth_rate_list[x])
            eps_list.append(new_eps_value)
            
        eps_list = np.array(eps_list)

        # Calculate Dividend Payout ratio (DPR of previous year - Annual payout Decrease)
        dpr_list = [float(self.payout_during_growth_year)/100 for dpr_value in np.arange(int(self.growth_year)+3)]
        for value in np.arange(20 - (int(self.growth_year)+3)):
            new_dpr_value = dpr_list[-1] - round(self.annual_payout_decrease, 8)
            dpr_list.append(round(new_dpr_value, 8)) 
        dpr_list.append(round(new_dpr_value, 8))
        dpr_list = np.array(dpr_list)
        # Calculate the Dividend per Share (DPS) as (EPS * DPR )
        dps_list = eps_list * dpr_list
        dps_list[20] = round(dps_list[20] / self.k_g, 8)

        # Calculate PV (DPS at present year/ ( 1 + cost of equity) ^number of years till present)
        years = np.arange(1, 22)
        pv = [dps/((1 + self.cost_of_equity_in_decimal)**years[yr]) for yr, dps in enumerate(dps_list)]
        pv = np.array(pv)

        # Calculate sum of pv (Summation of PV at year 1 to Pv at year 21 )
        sum_of_pv = round(np.sum(pv), 8)

        growth_rate_list.insert(0, "")
        growth_rate_list.insert(1, "")
        growth_rate_list.insert(2, "")
        growth_rate_list = np.array(growth_rate_list)
        ddm_table = pd.DataFrame({"Years":years, "Growth Rate":growth_rate_list, "EPS":eps_list, "Dividend Payout Ratio":dpr_list, 
                                "DPS":dps_list, "PV":pv})
        print("======================================================================")
        print("======================================================================")
        print(ddm_table)
        print("======================================================================")
        print("Sum of PV (DDM): ", sum_of_pv)
        print("======================================================================")
        print("======================================================================")
        self.try_again()
    
    # Model for DCF
    def dcf_model(self):
        print("======================================================================")
        print("============================ Select your data source ==============================")
        source = input("Press\n1. API input\n2. Manual input")
        if source == "1":
            self.fetch_company_data()
        elif source == "2":
            self.get_data_input()
        else:
            print("Invalid input. Try again")
            self.dcf_model()
        
    # Get manual input from user
    def get_data_input(self):
        print("Enter your free cash flow values")
        self.period1 = input("FCF Period 1: ")
        self.period2 = input("FCF Period 2: ")
        self.period3 = input("FCF Period 3: ")
        self.period4 = input("FCF Period 4: ")
        self.forecast_year = input("Forecast year: ")
        self.waac = input("WAAC: ")
        self.growth_rate = input("Growth Rate: ")
        self.share_outstanding = input("Share Outstanding: ")
        
        print("Enter your Cash and Cash Equivalent values")
        self.ccper1 = input("Cash and Cash Period 1: ") 
        self.ccper2 = input("Cash and Cash Period 2: ")
        self.ccper3 = input("Cash and Cash Period 3: ")
        self.ccper4 = input("Cash and Cash Period 4: ")
        print("Enter your Total Debt value")
        self.debt1 = input("Total Debt Period 1: ")
        self.debt2 = input("Total Debt Period 2: ")
        self.debt3 = input("Total Debt Period 3: ")
        self.debt4 = input("Total Debt Period 4: ")
        # Get input array of Free Cash Flow, Total Debt and Cash and Cash Equivalant
        self.fcf_input = [self.period1, self.period2, self.period3, self.period4]
        self.total_debt_input = [self.debt1, self.debt2, self.debt3, self.debt4]
        self.cc_equivalent_input = [self.ccper1, self.ccper2, self.ccper3, self.ccper4]
        # Calculate DCF values
        self.calculate_dcf()

    def get_API_data(self):
        # Define the ticker symbol
        ticker_symbol = input("Enter the company name e.g AAPL >>>")  # Example: Apple Inc.
        print("========================== Please wait while we fetch your data =========================")
        # Create a Ticker object
        ticker = yf.Ticker(ticker_symbol)
        try:
            # Get cash flow data
            cash_flow = ticker.cashflow
            # Get balance sheet data
            balance_sheet = ticker.balance_sheet
            # Get the number of shares outstanding
            shares_outstanding = ticker.info.get('sharesOutstanding')
        except Exception as e:
            print("An error occurred:", e)
            print("Retry again !!!")
            self.get_API_data()
        return cash_flow, balance_sheet, shares_outstanding
        
    def fetch_company_data(self):
        # Call the function to fetch the data.
        cash_flow, balance_sheet, shares_outstanding = self.get_API_data()
        # Extract the cash flow data
        self.fcf_input = cash_flow.loc["Free Cash Flow"].values
        # Extract the total debt data
        self.total_debt_input = balance_sheet.loc['Total Debt'].values
        # Extract the cash and cash equivalent data
        self.cc_equivalent_input = balance_sheet.loc["Cash And Cash Equivalents"].values
        # Get the shares outstanding value
        self.share_outstanding = shares_outstanding
        # Get the other values from manual input
        self.forecast_year = input("Enter Forecast Year value: ")
        self.waac = input("Enter WAAC value: ")
        self.growth_rate = input("Enter Growth Rate value: ")
        # Calculate DCF values
        self.calculate_dcf()

    def make_forecast(self, x, y, forecast_year):
            # Calculate the mean of x and y
            x_mean = np.mean(x)
            y_mean = np.mean(y)

            # Calculate the slope (m)
            numerator = np.sum((x - x_mean) * (y - y_mean))
            denominator = np.sum((x - x_mean) ** 2)
            slope = numerator / denominator

            # Calculate the y-intercept (b)
            intercept = y_mean - (slope * x_mean)
    
            # Perform a linear regression
            forecast_value = intercept + (slope * float(forecast_year))
            return forecast_value

    def calculate_dcf(self):
        # Print input data to output
        print("======================================================================")
        print("============================ Input Data ==============================")
        print("FCF input: ", self.fcf_input)
        print("Cash and Cash Equivalent input: ", self.cc_equivalent_input)
        print("Total Debt: ", self.total_debt_input)
        print("Growth Rate: ", self.growth_rate)
        print("Share Outstanding: ", self.share_outstanding)
        
        # Get the forecast value of Free Cash Flow equivalent
        y = np.array([float(period) for period in self.fcf_input])
        get_length = len(y)
        x = np.arange(1, get_length+1)

        fcf_forecast = self.make_forecast(x, y, self.forecast_year)
        print("======================================================================")
        print("======================================================================")
        print("Free Cash Flow Forecast: ", round(abs(fcf_forecast)))
        
        # Calculate the Terminal value (FCFx(1+growth rate))/(WACC-growth rate)
        growth_rate = float(self.growth_rate)/100
        waac = float(self.waac)/100
        terminal_val = abs((fcf_forecast * (1 + growth_rate)) / (waac - growth_rate))
        print("Terminal Value: ", round(terminal_val))
        
        # calculate the Discount factor 1/(1+WACC)^n
        disc_fac = 1 / ((1 + waac) ** x)
        d_fac5 = 1 / ((1 + waac) ** 5)
        print("Discount Factor Forecast: ", round(d_fac5, 9))
        
        # Calculate the PV of FCF (FCF x DF)
        pv_fcf = y * disc_fac
        pv_forec5 = fcf_forecast * d_fac5
        print("PV of FCF Forecast: ", round(abs(pv_forec5)))
        
        # Calculate the PV of TV (TV x DF)
        pv_tv = terminal_val * d_fac5
        print("PV of TV Forecast: " ,(round(pv_tv)))
        
        # Calculate the enterprise value (Sum of all PVs)
        enter_val = np.sum(pv_fcf) + pv_forec5 + pv_tv 
        print("Enterprise Value: ", round(enter_val))
        
        # Get the forecast value of cash and cash equivalent
        yc = np.array([float(period) for period in self.cc_equivalent_input])
        get_length = len(yc)
        xc = np.arange(1, get_length+1)
        cc_forecast = abs(self.make_forecast(xc, yc, self.forecast_year))
        print("Cash and Cash Equivalent Forecast: ", cc_forecast)
        # Get the forecast value of total debt
        ydt = np.array([float(period) for period in self.total_debt_input])
        get_length = len(ydt)
        xdt = np.arange(1, get_length+1)
        debt_forecast = abs(self.make_forecast(xdt, ydt, self.forecast_year))
        print("Total Debt Forecast: ", debt_forecast)
        
        # Calculate Net Debt (Total debt - Cash and cash equivalent)
        net_debt = debt_forecast - cc_forecast
        print("Net Debt: ",round(abs(net_debt)))
        
        # Calculate Equity value (Ent. Value - Net debt)
        equity_val = enter_val - net_debt
        print("Equity Value: ", round(equity_val))
        
        # Calculate Implied share price
        implied_share = equity_val / float(self.share_outstanding)
        print("Implied Share Price: ", round(implied_share, 2))
        
        print("======================================================================")
        print("======================================================================")
        self.try_again()

    def try_again(self):
        option = input("Enter your option:\n1. to return to main menu\n Any key to exit\n >>> ")
        if option == "1":
            self.mainmenu()
        else:
            sys.exit
            
        
ddm = DDM_DCF_model()


Enter your operation:
1. DDM model
2. DCF model
>>> 2


============================ Select your data source ==============================


Press
1. API input
2. Manual input 1
Enter the company name e.g AAPL >>> AAPL


========================== Please wait while we fetch your data =========================


Enter Forecast Year value:  5
Enter WAAC value:  354344
Enter Growth Rate value:  7.8


============================ Input Data ==============================
FCF input:  [99584000000.0 111443000000.0 92953000000.0 73365000000.0]
Cash and Cash Equivalent input:  [29965000000.0 23646000000.0 34940000000.0 38016000000.0]
Total Debt:  [111088000000.0 120069000000.0 124719000000.0 112436000000.0]
Growth Rate:  7.8
Share Outstanding:  15441899520
Free Cash Flow Forecast:  70049500000
Terminal Value:  21311218
Discount Factor Forecast:  0.0
PV of FCF Forecast:  0
PV of TV Forecast:  0
Enterprise Value:  28104707
Cash and Cash Equivalent Forecast:  40503500000.0
Total Debt Forecast:  119251500000.0
Net Debt:  78748000000
Equity Value:  -78719895293
Implied Share Price:  -5.1
